routes:
  /manifest/:
    template: manifest
    content_type: application/manifest+json

  /offline/:
    template: offline

  /notes/guides/:
    controller: channel
    filter: 'tag:hash-note+tag:guides'
    template: godo-notes-topic
    limit: 10

  /notes/korea/:
    controller: channel
    filter: 'tag:hash-note+tag:korea'
    template: godo-notes-topic
    limit: 10

  /notes/life/:
    controller: channel
    filter: 'tag:hash-note+tag:life'
    template: godo-notes-topic
    limit: 10

  /notes/travel/:
    controller: channel
    filter: 'tag:hash-note+tag:travel'
    template: godo-notes-topic
    limit: 10

  /notes/relocation/:
    controller: channel
    filter: 'tag:hash-note+tag:relocation'
    template: godo-notes-topic
    limit: 10

  /notes/tech/:
    controller: channel
    filter: 'tag:hash-note+tag:tech'
    template: godo-notes-topic
    limit: 10

  /notes/japan/:
    controller: channel
    filter: 'tag:hash-note+tag:japan'
    template: godo-notes-topic
    limit: 10

collections:
  /notes/:
    permalink: /{slug}/
    template: godo-notes
    filter: 'tag:hash-note'
    limit: 10

  /:
    permalink: /{slug}/
    template: index
    filter: 'tag:-hash-note'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
